In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
CDL = pd.read_csv('/Users/macbook/Library/CloudStorage/OneDrive-TheOhioStateUniversity/NLCD and CDL data/CDL_County_Cellwise_55141.csv')
NLCD = pd.read_csv('/Users/macbook/Library/CloudStorage/OneDrive-TheOhioStateUniversity/NLCD and CDL data/NLCD_County_Cellwise_SpatialJoin_55141.csv')

/var/folders/hs/y116vr4j4yg5fcthw_l99c5r0000gn/T/ipykernel_95066/3787423957.py:2: DtypeWarning: Columns (25,26,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  NLCD = pd.read_csv('/Users/macbook/Library/CloudStorage/OneDrive-TheOhioStateUniversity/NLCD and CDL data/NLCD_County_Cellwise_SpatialJoin_55141.csv')

In [3]:
# choosing 20000 rows from each dataset
CDL = CDL.sample(n=20000)
NLCD = NLCD.sample(n=20000)

# NLCD

In [4]:
NLCD.head()

,cell,GEOID,CSAFP,CBSAFP,LU_2001,LU_2004,LU_2006,LU_2008,LU_2011,LU_2013,...,MaxTexture,x,y,Slope_Degrees,FIPS_UA00,Name_UA00,Type_UA00,FIPS_UA10,Name_UA10,Type_UA10
1843712,161566984.0,55141,554,49220,Wetlands,Wetlands,Wetlands,Wetlands,Wetlands,Wetlands,...,not used,485220.0,2390820.0,0.001694,NaN,NaN,NaN,NaN,NaN,NaN
1527343,158099627.0,55141,554,49220,Wetlands,Wetlands,Wetlands,Wetlands,Wetlands,Wetlands,...,sandy over loamy,455010.0,2414820.0,0.004370,NaN,NaN,NaN,NaN,NaN,NaN
887384,151405720.0,55141,554,49220,Cropland,Cropland,Cropland,Cropland,Cropland,Cropland,...,fine-loamy,484140.0,2420520.0,0.030792,NaN,NaN,NaN,NaN,NaN,NaN
421370,145797511.0,55141,554,49220,Cropland,Cropland,Cropland,Cropland,Cropland,Cropland,...,fine-loamy,484410.0,2385900.0,0.014207,NaN,NaN,NaN,NaN,NaN,NaN
1201768,154665866.0,55141,554,49220,Forest,Forest,Forest,Forest,Forest,Forest,...,not used,468660.0,2396700.0,0.000132,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
NLCD.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 1843712 to 863798
Data columns (total 30 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cell           20000 non-null  float64
 1   GEOID          20000 non-null  int64
 2   CSAFP          20000 non-null  int64
 3   CBSAFP         20000 non-null  int64
 4   LU_2001        20000 non-null  object
 5   LU_2004        20000 non-null  object
 6   LU_2006        20000 non-null  object
 7   LU_2008        20000 non-null  object
 8   LU_2011        20000 non-null  object
 9   LU_2013        20000 non-null  object
 10  LU_2016        20000 non-null  object
 11  LU_2019        20000 non-null  object
 12  FIPS_cnty      20000 non-null  int64
 13  FIPS_csa18     20000 non-null  int64
 14  FIPS_cbsa18    20000 non-null  int64
 15  AREASYMBOL     20000 non-null  object
 16  SPATIALVER     20000 non-null  int64
 17  MUSYM          20000 non-null  object
 18  mapunit_key    20000 non-null  int64
 19  nccpi          20000 non-null  float64
 20  MaxTexture     19843 non-null  object
 21  x              20000 non-null  float64
 22  y              20000 non-null  float64
 23  Slope_Degrees  19992 non-null  float64
 24  FIPS_UA00      776 non-null    float64
 25  Name_UA00      776 non-null    object
 26  Type_UA00      776 non-null    object
 27  FIPS_UA10      812 non-null    float64
 28  Name_UA10      812 non-null    object
 29  Type_UA10      812 non-null    object
dtypes: float64(7), int64(8), object(15)
memory usage: 4.7+ MB

In [6]:
print(NLCD['LU_2006'].unique())

['Wetlands' 'Cropland' 'Forest' 'Developed' 'Pasture' 'Other']

# CDL

In [7]:
CDL.head()

,cell,x,y,GEOID,LU_2008,LU_2009,LU_2010,LU_2011,LU_2012,LU_2013,...,LU_2009_DRFEWS,LU_2010_DRFEWS,LU_2011_DRFEWS,LU_2012_DRFEWS,LU_2013_DRFEWS,LU_2014_DRFEWS,LU_2015_DRFEWS,LU_2016_DRFEWS,LU_2017_DRFEWS,LU_2018_DRFEWS
1935526,162030146.0,464220,2384580,55141,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,...,Forest,Forest,Forest,Wetlands,Forest,Forest,Wetlands,Forest,Forest,Forest
17354,140493455.0,473370,2425020,55141,Corn,Soybeans,Corn,Corn,Alfalfa,Alfalfa,...,Cropland,Cropland,Cropland,Pasture,Pasture,Pasture,Pasture,Pasture,Cropland,Cropland
1277560,155336250.0,478230,2397150,55141,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,...,Forest,Forest,Forest,Forest,Forest,Forest,Forest,Forest,Forest,Forest
785070,150303429.0,476250,2406600,55141,Soybeans,Corn,Soybeans,Corn,Soybeans,Corn,...,Cropland,Cropland,Cropland,Cropland,Cropland,Cropland,Cropland,Pasture,Pasture,Pasture
2191720,164619245.0,488970,2379720,55141,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,...,Forest,Forest,Forest,Forest,Forest,Forest,Forest,Forest,Forest,Forest

In [8]:
not_needed = CDL.columns[15:]
CDL.drop(not_needed, axis=1, inplace=True)
CDL.drop(CDL.columns[:4], axis=1, inplace=True)
CDL.head()

,LU_2008,LU_2009,LU_2010,LU_2011,LU_2012,LU_2013,LU_2014,LU_2015,LU_2016,LU_2017,LU_2018
1935526,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest
17354,Corn,Soybeans,Corn,Corn,Alfalfa,Alfalfa,Alfalfa,Alfalfa,Alfalfa,Corn,Corn
1277560,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest
785070,Soybeans,Corn,Soybeans,Corn,Soybeans,Corn,Peas,Corn,Alfalfa,Alfalfa,Alfalfa
2191720,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Evergreen Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest

In [9]:
products = CDL['LU_2018'].unique()

In [10]:
print(CDL.shape)
print(NLCD.shape)

(20000, 11)
(20000, 30)

# Separating the rows that we see changes in plantings

In [11]:
# Initialize empty data frames to store similar and dissimilar rows
similar_df = pd.DataFrame()
dissimilar_df = pd.DataFrame()

# Loop through each row of the data frame
for index, row in CDL.iterrows():
    
    # Check if inputs in columns 4-14 are the same
    if row[4:15].nunique() == 1:
        # If they're the same, add the row to the similar data frame
        similar_df = pd.concat([similar_df, row.to_frame().transpose()])
    else:
        # If they're not the same, add the row to the dissimilar data frame
        dissimilar_df = pd.concat([dissimilar_df, row.to_frame().transpose()])

In [12]:
print(similar_df.shape)
print(dissimilar_df.shape)
dissimilar_df.head()

(7680, 11)
(12320, 11)

,LU_2008,LU_2009,LU_2010,LU_2011,LU_2012,LU_2013,LU_2014,LU_2015,LU_2016,LU_2017,LU_2018
1935526,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest
17354,Corn,Soybeans,Corn,Corn,Alfalfa,Alfalfa,Alfalfa,Alfalfa,Alfalfa,Corn,Corn
785070,Soybeans,Corn,Soybeans,Corn,Soybeans,Corn,Peas,Corn,Alfalfa,Alfalfa,Alfalfa
2191720,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Evergreen Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest
1059665,Grassland/Pasture,Grassland/Pasture,Other Hay/Non Alfalfa,Alfalfa,Other Hay/Non Alfalfa,Other Hay/Non Alfalfa,Other Hay/Non Alfalfa,Other Hay/Non Alfalfa,Other Hay/Non Alfalfa,Fallow/Idle Cropland,Alfalfa

# Finding what we can have the year after every product

In [13]:
# Define a list to store the results for each product
product_results = []

# Loop through each product in the list
for product in products:

    # Identify which column has the current product entry
    product_col = None
    for col in dissimilar_df.columns:
        if product in dissimilar_df[col].unique():
            product_col = col
            break

    # If no entry for the current product is found, print an error message and skip to the next product
    if product_col is None:
        print(f"Error: no '{product}' entry found in dataframe.")
        continue

    # Find the column index of the column that comes after the current product entry
    product_col_idx = dissimilar_df.columns.get_loc(product_col)
    next_col_idx = product_col_idx + 1

    # If the current product entry is in the last column, print a message saying nothing can be planted the year after and skip to the next product
    if next_col_idx == len(dissimilar_df.columns):
        print(f"The '{product}' entry is in the last column. Nothing can be planted the year after.")
        continue

    # Otherwise, find the unique values that can be planted in the next year after the current product
    next_year_plantings = dissimilar_df.iloc[:, next_col_idx][dissimilar_df[product_col] == product].unique()

    # Store the results for the current product in the product_results list
    product_results.append((product, next_year_plantings))

# Print the results for each product
for product, next_year_plantings in product_results:
    print(f"The following can be planted in the year after '{product}':")
    for planting in next_year_plantings:
        print(planting)

The 'Cabbage' entry is in the last column. Nothing can be planted the year after.
The 'Sod/Grass Seed' entry is in the last column. Nothing can be planted the year after.
The following can be planted in the year after 'Deciduous Forest':
Deciduous Forest
Alfalfa
Evergreen Forest
Woody Wetlands
Grassland/Pasture
Oats
Mixed Forest
Shrubland
Soybeans
Other Hay/Non Alfalfa
Herbaceous Wetlands
Corn
Fallow/Idle Cropland
Open Water
Clover/Wildflowers
Winter Wheat
The following can be planted in the year after 'Corn':
Soybeans
Corn
Alfalfa
Winter Wheat
Other Hay/Non Alfalfa
Grassland/Pasture
Deciduous Forest
Potatoes
Oats
Herbaceous Wetlands
Fallow/Idle Cropland
Shrubland
Barley
Barren
Spring Wheat
Dry Beans
Peas
Developed/Open Space
Open Water
Sweet Corn
Clover/Wildflowers
Woody Wetlands
The following can be planted in the year after 'Alfalfa':
Soybeans
Alfalfa
Grassland/Pasture
Corn
Oats
Other Hay/Non Alfalfa
Winter Wheat
Deciduous Forest
Herbaceous Wetlands
Clover/Wildflowers
Woody Wetlands
Shrubland
Spring Wheat
Evergreen Forest
The following can be planted in the year after 'Developed/Low Intensity':
Developed/Low Intensity
Developed/Open Space
Developed/Med Intensity
The following can be planted in the year after 'Winter Wheat':
Corn
Alfalfa
Oats
Grassland/Pasture
Winter Wheat
Other Hay/Non Alfalfa
Soybeans
Herbaceous Wetlands
Deciduous Forest
Dry Beans
The following can be planted in the year after 'Grassland/Pasture':
Grassland/Pasture
Soybeans
Potatoes
Woody Wetlands
Deciduous Forest
Herbaceous Wetlands
Other Hay/Non Alfalfa
Alfalfa
Mixed Forest
Open Water
Corn
Oats
Evergreen Forest
Winter Wheat
Dry Beans
Shrubland
Misc Vegs & Fruits
Sweet Corn
Barley
Clover/Wildflowers
The following can be planted in the year after 'Herbaceous Wetlands':
Grassland/Pasture
Herbaceous Wetlands
Woody Wetlands
Alfalfa
Open Water
Deciduous Forest
Evergreen Forest
Soybeans
Shrubland
Mixed Forest
Other Hay/Non Alfalfa
Corn
Winter Wheat
Sweet Corn
Barley
Dry Beans
The following can be planted in the year after 'Other Hay/Non Alfalfa':
Alfalfa
Other Hay/Non Alfalfa
Soybeans
Grassland/Pasture
Herbaceous Wetlands
Corn
Deciduous Forest
Winter Wheat
Oats
Shrubland
Barren
The following can be planted in the year after 'Open Water':
Open Water
Herbaceous Wetlands
Woody Wetlands
Grassland/Pasture
Corn
The following can be planted in the year after 'Woody Wetlands':
Deciduous Forest
Herbaceous Wetlands
Woody Wetlands
Mixed Forest
Other Hay/Non Alfalfa
Grassland/Pasture
Evergreen Forest
Open Water
Shrubland
Alfalfa
The following can be planted in the year after 'Developed/Open Space':
Developed/Open Space
Developed/Low Intensity
Soybeans
Corn
The following can be planted in the year after 'Potatoes':
Corn
Sweet Corn
Alfalfa
Soybeans
Dry Beans
Peas
Winter Wheat
The following can be planted in the year after 'Soybeans':
Corn
Other Hay/Non Alfalfa
Barley
Grassland/Pasture
Alfalfa
Winter Wheat
Oats
Developed/Open Space
Dry Beans
Potatoes
Soybeans
Spring Wheat
Herbaceous Wetlands
Deciduous Forest
Clover/Wildflowers
Evergreen Forest
Fallow/Idle Cropland
The following can be planted in the year after 'Evergreen Forest':
Deciduous Forest
Evergreen Forest
Mixed Forest
Woody Wetlands
Herbaceous Wetlands
Grassland/Pasture
Open Water
The following can be planted in the year after 'Mixed Forest':
Deciduous Forest
Mixed Forest
Evergreen Forest
Woody Wetlands
Grassland/Pasture
Herbaceous Wetlands
The following can be planted in the year after 'Shrubland':
Grassland/Pasture
Deciduous Forest
Woody Wetlands
Corn
Shrubland
Herbaceous Wetlands
Alfalfa
The following can be planted in the year after 'Fallow/Idle Cropland':
Winter Wheat
Corn
Alfalfa
Deciduous Forest
Barren
Grassland/Pasture
Soybeans
Oats
Herbaceous Wetlands
Dry Beans
The following can be planted in the year after 'Developed/Med Intensity':
Developed/Med Intensity
Developed/Open Space
Developed/Low Intensity
Developed/High Intensity
Grassland/Pasture
The following can be planted in the year after 'Developed/High Intensity':
Developed/High Intensity
The following can be planted in the year after 'Barren':
Corn
Grassland/Pasture
Soybeans
The following can be planted in the year after 'Dry Beans':
Potatoes
Dry Beans
Grassland/Pasture
Winter Wheat
Alfalfa
Soybeans
Cucumbers
Corn
The following can be planted in the year after 'Clover/Wildflowers':
Alfalfa
Other Hay/Non Alfalfa
Corn
Grassland/Pasture
The following can be planted in the year after 'Oats':
Alfalfa
Fallow/Idle Cropland
Grassland/Pasture
Deciduous Forest
Corn
Winter Wheat
Other Hay/Non Alfalfa
Soybeans
The following can be planted in the year after 'Triticale':
Alfalfa
The following can be planted in the year after 'Cucumbers':
Dry Beans
The following can be planted in the year after 'Herbs':
Potatoes
The following can be planted in the year after 'Rye':
Developed/Low Intensity
Alfalfa
Deciduous Forest
The following can be planted in the year after 'Christmas Trees':
Grassland/Pasture
The following can be planted in the year after 'Barley':
Alfalfa
Herbaceous Wetlands
The following can be planted in the year after 'Sweet Potatoes':
Sweet Corn
Dry Beans
Corn

In [14]:
print(product_results[1])
np.shape(product_results)

('Corn', array(['Soybeans', 'Corn', 'Alfalfa', 'Winter Wheat',
       'Other Hay/Non Alfalfa', 'Grassland/Pasture', 'Deciduous Forest',
       'Potatoes', 'Oats', 'Herbaceous Wetlands', 'Fallow/Idle Cropland',
       'Shrubland', 'Barley', 'Barren', 'Spring Wheat', 'Dry Beans',
       'Peas', 'Developed/Open Space', 'Open Water', 'Sweet Corn',
       'Clover/Wildflowers', 'Woody Wetlands'], dtype=object))

/Users/macbook/anaconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py:2009: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape

(30, 2)

In [15]:
for i in range(0, np.shape(product_results)[0]):
    difference = np.setdiff1d(products, product_results[i][1])
    print('We cant have the following after', product_results[i][0])
    print(difference)
    print('\n')

We cant have the following after Deciduous Forest
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans' 'Herbs'
 'Potatoes' 'Rye' 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale']


We cant have the following after Corn
['Cabbage' 'Christmas Trees' 'Cucumbers' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity' 'Evergreen Forest'
 'Herbs' 'Mixed Forest' 'Rye' 'Sod/Grass Seed' 'Sweet Potatoes'
 'Triticale']


We cant have the following after Alfalfa
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Fallow/Idle Cropland' 'Herbs' 'Mixed Forest' 'Open Water' 'Potatoes'
 'Rye' 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale']


We cant have the following after Developed/Low Intensity
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Dry Beans' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Winter Wheat
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers'
 'Cucumbers' 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Herbs' 'Mixed Forest' 'Open Water' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale'
 'Woody Wetlands']


We cant have the following after Grassland/Pasture
['Barren' 'Cabbage' 'Christmas Trees' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Fallow/Idle Cropland'
 'Herbs' 'Rye' 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale']


We cant have the following after Herbaceous Wetlands
['Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Fallow/Idle Cropland'
 'Herbs' 'Oats' 'Potatoes' 'Rye' 'Sod/Grass Seed' 'Sweet Potatoes'
 'Triticale']


We cant have the following after Other Hay/Non Alfalfa
['Barley' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Herbs' 'Mixed Forest'
 'Open Water' 'Potatoes' 'Rye' 'Sod/Grass Seed' 'Sweet Potatoes'
 'Triticale' 'Woody Wetlands']


We cant have the following after Open Water
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Herbs' 'Mixed Forest' 'Oats'
 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland' 'Sod/Grass Seed'
 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat']


We cant have the following after Woody Wetlands
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Corn'
 'Cucumbers' 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Fallow/Idle Cropland' 'Herbs' 'Oats' 'Potatoes' 'Rye' 'Sod/Grass Seed'
 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat']


We cant have the following after Developed/Open Space
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Med Intensity' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Grassland/Pasture'
 'Herbaceous Wetlands' 'Herbs' 'Mixed Forest' 'Oats' 'Open Water'
 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland' 'Sod/Grass Seed'
 'Sweet Potatoes' 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Potatoes
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers'
 'Cucumbers' 'Deciduous Forest' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Evergreen Forest' 'Fallow/Idle Cropland'
 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs' 'Mixed Forest' 'Oats'
 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland'
 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale' 'Woody Wetlands']


We cant have the following after Soybeans
['Barren' 'Cabbage' 'Christmas Trees' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Herbs' 'Mixed Forest' 'Open Water' 'Rye'
 'Shrubland' 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale'
 'Woody Wetlands']


We cant have the following after Evergreen Forest
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Fallow/Idle Cropland' 'Herbs' 'Oats'
 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland' 'Sod/Grass Seed'
 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat']


We cant have the following after Mixed Forest
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Fallow/Idle Cropland' 'Herbs' 'Oats'
 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland'
 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat']


We cant have the following after Shrubland
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers'
 'Cucumbers' 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Herbs' 'Mixed Forest' 'Oats'
 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Sod/Grass Seed'
 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat']


We cant have the following after Fallow/Idle Cropland
['Barley' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Cucumbers'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Herbs' 'Mixed Forest' 'Open Water'
 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland' 'Sod/Grass Seed'
 'Sweet Potatoes' 'Triticale' 'Woody Wetlands']


We cant have the following after Developed/Med Intensity
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Deciduous Forest' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Developed/High Intensity
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Deciduous Forest'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Barren
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale'
 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Dry Beans
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers'
 'Deciduous Forest' 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Herbaceous Wetlands' 'Herbs' 'Mixed Forest'
 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Rye' 'Shrubland'
 'Sod/Grass Seed' 'Sweet Potatoes' 'Triticale' 'Woody Wetlands']


We cant have the following after Clover/Wildflowers
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers'
 'Cucumbers' 'Deciduous Forest' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Herbaceous Wetlands' 'Herbs' 'Mixed Forest'
 'Oats' 'Open Water' 'Potatoes' 'Rye' 'Shrubland' 'Sod/Grass Seed'
 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Oats
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers'
 'Cucumbers' 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Herbaceous Wetlands' 'Herbs' 'Mixed Forest' 'Oats'
 'Open Water' 'Potatoes' 'Rye' 'Shrubland' 'Sod/Grass Seed'
 'Sweet Potatoes' 'Triticale' 'Woody Wetlands']


We cant have the following after Triticale
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Corn'
 'Cucumbers' 'Deciduous Forest' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Cucumbers
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Herbs
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Grassland/Pasture'
 'Herbaceous Wetlands' 'Herbs' 'Mixed Forest' 'Oats' 'Open Water'
 'Other Hay/Non Alfalfa' 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans'
 'Sweet Potatoes' 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Rye
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Corn'
 'Cucumbers' 'Developed/High Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Christmas Trees
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Corn' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Dry Beans'
 'Evergreen Forest' 'Fallow/Idle Cropland' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']


We cant have the following after Barley
['Barley' 'Barren' 'Cabbage' 'Christmas Trees' 'Clover/Wildflowers' 'Corn'
 'Cucumbers' 'Deciduous Forest' 'Developed/High Intensity'
 'Developed/Low Intensity' 'Developed/Med Intensity'
 'Developed/Open Space' 'Dry Beans' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbs' 'Mixed Forest' 'Oats'
 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes' 'Rye' 'Shrubland'
 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes' 'Triticale' 'Winter Wheat'
 'Woody Wetlands']


We cant have the following after Sweet Potatoes
['Alfalfa' 'Barley' 'Barren' 'Cabbage' 'Christmas Trees'
 'Clover/Wildflowers' 'Cucumbers' 'Deciduous Forest'
 'Developed/High Intensity' 'Developed/Low Intensity'
 'Developed/Med Intensity' 'Developed/Open Space' 'Evergreen Forest'
 'Fallow/Idle Cropland' 'Grassland/Pasture' 'Herbaceous Wetlands' 'Herbs'
 'Mixed Forest' 'Oats' 'Open Water' 'Other Hay/Non Alfalfa' 'Potatoes'
 'Rye' 'Shrubland' 'Sod/Grass Seed' 'Soybeans' 'Sweet Potatoes'
 'Triticale' 'Winter Wheat' 'Woody Wetlands']

# Finding out hom many times changes occur in the same field

### Non-unique:

In [83]:
# Define a function that counts the number of changes in a row
def count_changes(row):
    counter = 0
    for i in range(len(row)-1):
        if row[i] != row[i+1]:
            counter += 1
    return counter

# Apply the count_changes function to each row in the dataframe using the apply() method and store the results in a new column called 'changes'
dissimilar_df['changes'] = dissimilar_df.apply(count_changes, axis=1)

# Print the resulting dataframe
dissimilar_df.head()

,LU_2008,LU_2009,LU_2010,LU_2011,LU_2012,LU_2013,LU_2014,LU_2015,LU_2016,LU_2017,LU_2018,changes
1387245,Grassland/Pasture,Corn,Herbaceous Wetlands,Soybeans,Corn,Corn,Soybeans,Corn,Corn,Corn,Soybeans,7
370916,Alfalfa,Alfalfa,Alfalfa,Corn,Corn,Corn,Corn,Alfalfa,Alfalfa,Alfalfa,Alfalfa,2
1287165,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,3
1840467,Evergreen Forest,Evergreen Forest,Evergreen Forest,Mixed Forest,Mixed Forest,Evergreen Forest,Mixed Forest,Evergreen Forest,Woody Wetlands,Evergreen Forest,Evergreen Forest,6
44684,Developed/Low Intensity,Developed/Open Space,Developed/Open Space,Developed/Low Intensity,Developed/Open Space,Developed/Open Space,Developed/Open Space,Developed/Open Space,Developed/Open Space,Developed/Low Intensity,Developed/Open Space,5

In [84]:
print('In average, we see ' + str(np.mean(dissimilar_df['changes'])) + ' changes per row')

In average, we see 5.518993428434044 changes per row

### Unique:

In [85]:
# Define a function that counts the number of unique changes in a row
def count_unique_changes(row):
    changes = {}
    for i in range(len(row)-1):
        if row[i] != row[i+1]:
            pair = (row[i], row[i+1])
            if pair not in changes:
                changes[pair] = 1
    return len(changes)-1

# Apply the count_unique_changes function to each row in the dataframe using the apply() method and store the results in a new column called 'unique_changes_count'
dissimilar_df['unique_changes_count'] = dissimilar_df.apply(count_unique_changes, axis=1)

# Print the resulting dataframe
dissimilar_df.head()

,LU_2008,LU_2009,LU_2010,LU_2011,LU_2012,LU_2013,LU_2014,LU_2015,LU_2016,LU_2017,LU_2018,changes,unique_changes_count
1387245,Grassland/Pasture,Corn,Herbaceous Wetlands,Soybeans,Corn,Corn,Soybeans,Corn,Corn,Corn,Soybeans,7,5
370916,Alfalfa,Alfalfa,Alfalfa,Corn,Corn,Corn,Corn,Alfalfa,Alfalfa,Alfalfa,Alfalfa,2,2
1287165,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Woody Wetlands,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,Deciduous Forest,3,2
1840467,Evergreen Forest,Evergreen Forest,Evergreen Forest,Mixed Forest,Mixed Forest,Evergreen Forest,Mixed Forest,Evergreen Forest,Woody Wetlands,Evergreen Forest,Evergreen Forest,6,4
44684,Developed/Low Intensity,Developed/Open Space,Developed/Open Space,Developed/Low Intensity,Developed/Open Space,Developed/Open Space,Developed/Open Space,Developed/Open Space,Developed/Open Space,Developed/Low Intensity,Developed/Open Space,5,2

In [87]:
print('In average, we see ' + str(np.mean(dissimilar_df['unique_changes_count'])) + ' unique changes per row')

In average, we see 4.266869690655554 unique changes per row

# Finding the changes between two given years

In [21]:
# create a list of year columns
years = dissimilar_df.columns

# loop through the years
for i in range(len(years) - 1):
    # create a new data frame with just the fields for the current year and the next year
    current_year = years[i]
    next_year = years[i+1]
    df_year = dissimilar_df[[current_year, next_year]]

    # get the most frequent changes from the current year to the next year
    changes = df_year.groupby([current_year, next_year]).size().reset_index(name='count')
    changes = changes.sort_values(by='count', ascending=False)

    # store the results in a separate data frame
    df_changes = pd.DataFrame({'From': changes[current_year], 'To': changes[next_year], 'Count': changes['count']})

    # write the data frame to a CSV file
    filename = 'changes_{}_{}.csv'.format(current_year[-4:], next_year[-4:])
    df_changes.to_csv(filename, index=False)

In [26]:
# read in the CSV file for the changes from 2008 to 2009
df_changes = pd.read_csv('changes_2009_2010.csv')

# only keep rows where the "From" column is different from the "To" column
df_changes = df_changes[df_changes['From'] != df_changes['To']]

# print the resulting data frame
df_changes.head(10)

# WHY WE SEE LOTS OF CORN->SOYBEANS AND SOYBEANS->CORN CHANGES:
# Compared to other crops, corn needs lots of nutrients, especially nitrogen. 
# This makes soybeans a good crop to alternate with corn, because soybeans have 
# nodules on their roots that host bacteria that fix atmospheric nitrogen.

                     From                     To  Count
4                    Corn               Soybeans    488
5          Woody Wetlands       Deciduous Forest    408
6                 Alfalfa      Grassland/Pasture    401
7        Deciduous Forest         Woody Wetlands    355
8                Soybeans                   Corn    353
11      Grassland/Pasture       Deciduous Forest    275
12                Alfalfa  Other Hay/Non Alfalfa    262
14       Deciduous Forest      Grassland/Pasture    233
15  Other Hay/Non Alfalfa      Grassland/Pasture    229
16                Alfalfa                   Corn    229